name: Android CI/CD

on:
  push:
    branches:
      - main  # Or another default branch
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Create local.properties file
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Build and test
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease
          ./gradlew test

      - name: Locate APK file
        id: retrieve-path
        run: echo "path=$(find app/build/outputs/apk/ -type f -name '*.apk' | head -n 1)" >> $GITHUB_OUTPUT

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ steps.retrieve-path.outputs.path }}
